role = "client"
log_level = "info"
http_pprof_addr = "localhost:6060" # disable if empty

[server]
protocol = "tcp"
listen_downstream_addr = ":8022"
downstream_selection_strategy = "conn" # conn or bandwidth, choose less

[client]
conn_pool_size = 8

[[client.upstream]]
name = "sh-tonylu-cloud" # unique name for client-side
protocol = "tcp"
addr = "example.com:8022"
retry_interval = 5 # in secound
endpoints = [ "*" ]  # registerd endpoint, "*" means all, empty is not allowed

[[client.upstream]]
name = "local"
protocol = "tcp"
addr = "example.com:8022"
max_retries = 30
retry_interval = 5
endpoints = [ "ssh" ]  # registerd endpoint, "*" means all, empty is not allowed

[[endpoint]]
name = "ssh"
mode = "downstream" # downstream or direct
protocol = "tcp"
listen = ":22"
target = "192.168.1.1:22"
